apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-ingress-controller
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-lb
    component: ingress-controller
    type: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: tectonic-lb
        component: ingress-controller
        type: nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  k8s-app: tectonic-lb
              topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx-ingress-lb
          image: ${ingress_controller_image}
          args:
          - /nginx-ingress-controller
          - --configmap=$(POD_NAMESPACE)/tectonic-custom-error
          - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
          - --default-ssl-certificate=tectonic-system/tectonic-ingress-tls-secret
          - --ingress-class=tectonic
          # use downward API
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: health
              containerPort: 10254
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 1
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
