---
sudo: required
language: bash
services:
  - docker
env:
  global:
    - BAZEL_IMG="quay.io/coreos/tectonic-builder:bazel-v0.3"
branches:
  only:
    - master
jobs:
  include:
    - stage: Lint & Test
      name: Terraform lint
      script: docker run -v $(pwd):/data -t quay.io/coreos/tflint
    - script: ./hack/yaml-lint.sh
      name: YAML lint
    - script: ./hack/shellcheck.sh
      name: shellcheck
    - script: ./hack/tf-fmt.sh
      name: Terraform format
    - script: ./hack/gotest.sh
      name: Installer unit tests
    - script: "docker run -v $PWD:/go/src/github.com/openshift/installer -w /go/src/github.com/openshift/installer quay.io/coreos/golang-testing go vet ./installer/..."
      name: Go vet
    - script: "docker run -v $PWD:$PWD -w $PWD quay.io/coreos/golang-testing golint -set_exit_status installer/..."
      name: Go lint
    - stage: Build
      script: "chmod 0777 $PWD && docker run -v $PWD:$PWD:rw -w $PWD $BAZEL_IMG bazel build tarball"
      name: Build tarball
