ignored = [
  "github.com/openshift/installer/tests*",
  "github.com/openshift/installer/pkg/terraform/exec*"
]

required = [
  #needed in pkg/terraform/exec
  "golang.org/x/net/html/charset"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.8.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.14"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v29.0.0"

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  name = "github.com/libvirt/libvirt-go"
  version = "4.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "github.com/openshift/cluster-api"
  branch = "openshift-4.2-cluster-api-0.1.0"

[[constraint]]
  name = "sigs.k8s.io/cluster-api-provider-aws"
  source = "https://github.com/openshift/cluster-api-provider-aws.git"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/cluster-api-provider-libvirt"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "k8s.io/utils"
  revision = "4c3feeb576b06ef8fea769809bd3db5e5e78dc23"

[[constraint]]
  name = "github.com/gophercloud/utils"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "release-4.2"
  name = "github.com/openshift/cloud-credential-operator"

[[constraint]]
  branch = "master"
  name = "sigs.k8s.io/cluster-api-provider-openstack"
  source = "https://github.com/openshift/cluster-api-provider-openstack.git"

[[constraint]]
  branch = "master"
  name = "sigs.k8s.io/cluster-api-provider-azure"
  source = "https://github.com/openshift/cluster-api-provider-azure.git"

[[constraint]]
  name = "github.com/pkg/sftp"
  version = "1.10.0"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]  
  branch = "master"
  name = "github.com/openshift/cluster-api-provider-gcp"

[[constraint]]  
  name = "github.com/containers/image"
  version = "2.0.0"

[[constraint]]
  name = "github.com/metal3-io/cluster-api-provider-baremetal"
  source = "https://github.com/openshift/cluster-api-provider-baremetal/pkg/apis"

[[constraint]]
  branch = "master"
  name = "github.com/metal3-io/baremetal-operator"
  source = "https://github.com/openshift/baremetal-operator"
