ignored = [
  "github.com/openshift/installer/tests*",
  "github.com/openshift/installer/pkg/terraform/exec*"
]

required = [
  #needed in pkg/terraform/exec
  "golang.org/x/net/html/charset"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.8.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.14"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "25.1.0"

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  name = "github.com/gregjones/httpcache"
  source = "https://github.com/wking/httpcache"
  revision = "8d10353503cd5426136ad4880b523785bb76e8c7"

[[constraint]]
  name = "github.com/libvirt/libvirt-go"
  version = "4.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "github.com/openshift/cluster-api"
  revision = "91fca585a85b163ddfd119fd09c128c9feadddca"

[[constraint]]
  name = "sigs.k8s.io/cluster-api-provider-aws"
  source = "https://github.com/openshift/cluster-api-provider-aws.git"
  revision = "15fe4b4ea5636f8516c238490fc6a85d44161181"

[[constraint]]
  name = "github.com/openshift/cluster-api-provider-libvirt"
  revision = "c23986b36a2521cd69ac22d7adb74a22bca9f7aa"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "k8s.io/utils"
  revision = "4c3feeb576b06ef8fea769809bd3db5e5e78dc23"

[[constraint]]
  name = "github.com/gophercloud/utils"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "master"
  name = "sigs.k8s.io/cluster-api-provider-openstack"
  source = "https://github.com/openshift/cluster-api-provider-openstack.git"

[[constraint]]
  branch = "openshiftnocluster"
  name = "sigs.k8s.io/cluster-api-provider-azure"
  source = "https://github.com/awesomenix/cluster-api-provider-azure.git"
