ignored = ["github.com/openshift/installer/tests*"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.6.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.39"

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/tectonic-config"

[[constraint]]
  name = "github.com/libvirt/libvirt-go"
  version = "4.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[override]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  branch = "master"
[[constraint]]
  name = "sigs.k8s.io/cluster-api-provider-aws"
  source = "https://github.com/openshift/cluster-api-provider-aws.git"
  branch = "master"
[[constraint]]
  name = "github.com/openshift/cluster-api-provider-libvirt"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "github.com/openshift/hive"
  revision = "8c7844d9b61c35f53bab561f5ce4d879fef86ec6"

[[constraint]]
  name = "k8s.io/utils"
  revision = "4c3feeb576b06ef8fea769809bd3db5e5e78dc23"

[[constraint]]
  name = "github.com/openshift/cluster-network-operator"
  revision = "fb8b55a1072436a51b153de9acf5bf5525efcf83"
