apiVersion: v1
kind: ConfigMap
metadata:
  name: tectonic-monitoring
  namespace: tectonic-system
data:
  config.yaml: |+
    prometheusOperator:
      baseImage: ${prometheus_operator_base_image}
      prometheusConfigReloaderBaseImage: ${prometheus_config_reload_base_image}
      configReloaderBaseImage: ${config_reload_base_image}
    prometheusK8s:
      baseImage: ${prometheus_base_image}
    alertmanagerMain:
      baseImage: ${alertmanager_base_image}
    ingress:
      baseAddress: ${console_base_host}
    auth:
      baseImage: ${tectonic_monitoring_auth_base_image}
    nodeExporter:
      baseImage: ${node_exporter_base_image}
    kubeStateMetrics:
      baseImage: ${kube_state_metrics_base_image}
      addonResizerBaseImage: ${addon_resizer_base_image}
