apiVersion: tco.coreos.com/v1
kind: ChannelOperatorConfig
metadata:
  name: default
  namespace: tectonic-system
server: ${update_server}
channel: ${update_channel}
appID: ${update_app_id}
automaticUpdate: false
triggerUpdate: false
triggerUpdateCheck: false
updateCheckInterval: 2700
