kind: VersionManifestV1
versions:
  k8s:
    1.6:
        docker: [ "1.12"]
    1.7:
        docker: [ "1.12" ]
    1.8:
        docker: [ "17.03", "1.12"]
    1.9:
        docker: [ "17.03", "1.12"]
    3.10:
        docker: [ "17.03", "1.12"]