apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-identity
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-identity
    component: identity
spec:
  replicas: 1
  # New identity pods must be healthy for 30 seconds
  # before they're marked as ready.
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      # During a rolling update every deployed pod must be
      # ready before the update terminates an existing pod.
      maxUnavailable: 0
  template:
    metadata:
      name: tectonic-identity
      labels:
        k8s-app: tectonic-identity
        component: identity
    spec:
      volumes:
      - name: config
        configMap:
          name: tectonic-identity
          items:
          - key: config.yaml
            path: config.yaml
      - name: tectonic-identity-grpc-server-secret
        secret:
          secretName: tectonic-identity-grpc-server-secret
      containers:
      - name: tectonic-identity
        imagePullPolicy: IfNotPresent
        image: ${identity_image}
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/config.yaml"]
        volumeMounts:
        - name: config
          mountPath: /etc/dex
        - name: tectonic-identity-grpc-server-secret
          mountPath: /etc/tectonic-identity-grpc-server-secret
          readOnly: true
        ports:
        - containerPort: 5556
          protocol: TCP
        - containerPort: 5557
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /identity/healthz
            port: 5556
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
      # For development, assume that all images we build ourselves are under a
      # private registry.
      imagePullSecrets:
      - name: coreos-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
