kind: ConfigMap
apiVersion: v1
metadata:
  name: tectonic-config
  namespace: tectonic-system
data:
  clusterID: "${cluster_id}"
  clusterName: "${cluster_name}"
  installerPlatform: "${platform}"
  certificatesStrategy: "${certificates_strategy}"
  tectonicUpdaterEnabled: "${tectonic_updater_enabled}"
  consoleBaseAddress: "https://${console_base_address}"
  kubeAPIServerURL: "${kube_apiserver_url}"
  tectonicVersion: "${tectonic_version}"
  dexAPIHost: "${identity_api_service}:5557"
