apiVersion: v1
kind: Secret
metadata:
  name: tectonic-ingress-tls
  namespace: tectonic-ingress
type: Opaque
data:
  tls.crt: ${ingress_tls_cert}
  tls.key: ${ingress_tls_key}
  bundle.crt: ${ingress_tls_bundle}