apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tectonic-alm-operator
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-alm-operator
    managed-by-channel-operator: "true"
  annotations:
    tectonic-operators.coreos.com/upgrade-behaviour: 'CreateOrUpgrade'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: tectonic-alm-operator
  template:
    metadata:
      labels:
        k8s-app: tectonic-alm-operator
    spec:
      imagePullSecrets:
        - name: coreos-pull-secret
      containers:
      - name: tectonic-alm-operator
        image: ${tectonic_alm_operator_image}
        command:
        - /tectonic-x-operator
        - --operator-name=tectonic-alm-operator
        - --appversion-name=tectonic-alm-operator
        - --v=2
