apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-network
  namespace: tectonic-system 
  labels:
    managed-by-channel-operator: "true"
spec:
  desiredVersion: ${tectonic_network_operator_version}
  paused: false
status:
  currentVersion: 
  paused: false
