apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
data:
  apiserver.key: ${apiserver_key}
  apiserver.crt: ${apiserver_cert}
  service-account.pub: ${serviceaccount_pub}
  ca.crt: ${ca_cert}
  etcd-client-ca.crt: ${etcd_ca_cert}
  etcd-client.crt: ${etcd_client_cert}
  etcd-client.key: ${etcd_client_key}
