apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: kubernetes-addon
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
spec:
  desiredVersion: ${kubernetes_addon_operator_version}
  paused: false
status:
  currentVersion: 
  paused: false
