apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-cluo-operator
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
  annotations:
    tectonic-operators.coreos.com/upgrade-behaviour: 'CreateOrUpgrade'
spec:
  desiredVersion: ${tectonic_cluo_operator_version}
  paused: false
