apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-monitoring
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
spec:
  desiredVersion: ${monitoring_version}
  paused: false
status:
  currentVersion: ${monitoring_version}
  paused: false
