apiVersion: v1
baseDomain: Enter here the base domain
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: Enter here the cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: Enter here the machine network CIDR
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  kubevirt:
    apiVIP: Enter here the API virtual IP
    ingressVIP: Enter here the Ingress virtual IP
    namespace: Enter here the namespace to create the tenant cluster resources in
    networkName: Enter here the network (NAD name) to be used by the tenant cluster
    storageClass: Enter here the storage class used in the infra cluster
publish: External
pullSecret: Enter pullSecret here, You can get this secret from https://cloud.redhat.com/openshift/install/pull-secret
sshKey: Enter here your ssh public key
