apiVersion: v1
kind: Service
metadata:
  name: tectonic-console
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-console
    component: ui
spec:
  selector:
    k8s-app: tectonic-console
    component: ui
  ports:
  - name: tectonic-console
    protocol: TCP
    port: 80
    targetPort: 8080
