apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: tectonic-system
  labels:
    app: node-exporter
    k8s-app: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
