apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tectonic-monitoring-auth-prometheus
  namespace: tectonic-system
  labels:
    k8s-app: tectonic-monitoring-auth-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tectonic-monitoring-auth-prometheus
  template:
    metadata:
      labels:
        k8s-app: tectonic-monitoring-auth-prometheus
    spec:
      containers:
      - name: auth-proxy
        image: ${tectonic_monitoring_auth_image}
        env:
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: "tectonic-identity"
              key: "consoleClientID"
        - name: CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: "tectonic-identity"
              key: "consoleSecret"
        - name: OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
              name: "tectonic-identity"
              key: "issuer"
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: "tectonic-monitoring-auth"
              key: "cookie_secret"
        args:
        - '-provider=oidc'
        - '-client-id=$(CLIENT_ID)'
        - '-client-secret=$(CLIENT_SECRET)'
        - '-cookie-secret=$(COOKIE_SECRET)'
        - '-external-url=${prometheus_external_url}'
        - '-proxy-prefix=/auth'
        - '-pass-host-header=true'
        - '-pass-user-headers=true'
        - '-pass-basic-auth=false'
        - '-cookie-name=_tectonic_monitoring_auth'
        - '-cookie-domain=${console_base_address}'
        - '-cookie-expire=8h0m0s'
        - '-email-domain=*'
        - '-redirect-url=${prometheus_callback}'
        - '-oidc-issuer-url=$(OIDC_ISSUER_URL)'
        - '-http-address=http://0.0.0.0:4180'
        - '-upstream=http://prometheus.tectonic-system.svc:9090'
        - '-ssl-insecure-skip-verify'
        ports:
        - name: http
          containerPort: 4180
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 20Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
