name: Power VS Verify

on:
  pull_request:
    branches: [ add-ipi ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint

    - name: Run go fmt & lint
      run: |
        go fmt -mod=readonly ./...
        git diff HEAD
        if [ `git diff HEAD --name-only | wc -l` -gt 0 ]; then exit 1; fi
        golint -set_exit_status=1 `go list -mod=readonly ./... | grep -v /vendor/`

    - name: Build
      run: |
        go mod vendor
        ./hack/build.sh
